// Auto-extracted from factors.json on 2026-05-13
// Filtered to: type ∈ {SYMPTOM, SIGN, RISK_FACTOR}, RISK_ASSESSMENT assignment, not CHILDHOOD_ONLY, not deleted
// Total: 387 factors
export const FACTORS = [
  { id: "multipleMoles", name: ">100 moles", type: "RISK_FACTOR", categories: ["SKIN"] },
  { id: "abdominalBloating", name: "Abdominal bloating or distension", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "abdominalPain", name: "Abdominal pain", type: "SYMPTOM", categories: ["GASTROINTESTINAL", "GYNAECOLOGICAL"] },
  { id: "abdominalPainRadiatingToBack", name: "Abdominal pain radiating to back", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "abnormalLookingCervix", name: "Abnormal looking cervix", type: "SIGN", categories: ["GYNAECOLOGICAL"] },
  { id: "abnormalVaginalBleeding", name: "Abnormal vaginal bleeding (pre or peri menopausal)", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "acidBrash", name: "Acid brash", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "alcoholInducedLymphNodePain", name: "Alcohol-induced lymph node pain", type: "SYMPTOM", categories: ["HAEMATOLOGICAL"] },
  { id: "analMass", name: "Anal mass", type: "SIGN", categories: ["GASTROINTESTINAL"] },
  { id: "analUlceration", name: "Anal ulceration", type: "SIGN", categories: ["GASTROINTESTINAL"] },
  { id: "appearanceCervicalCancer", name: "Appearance of cervix consistent with cancer", type: "SIGN", categories: ["GYNAECOLOGICAL"] },
  { id: "appetiteLoss", name: "Appetite loss", type: "SYMPTOM", categories: ["GYNAECOLOGICAL", "CHEST", "NON_SPECIFIC"] },
  { id: "asbestos", name: "Asbestos exposure", type: "RISK_FACTOR", categories: ["CHEST"] },
  { id: "ascites", name: "Ascites", type: "SIGN", categories: ["GYNAECOLOGICAL"] },
  { id: "majorRiskFactorsForEndometrialCancer", name: "At least one major risk factor for Endometrial Cancer: BMI ≥ 40; Genetic predisposition (Lynch / Cowden syndrome); Estrogen-only HRT for > 6 months in women with a uterus; Tricycling HRT (quarterly progestogen) for > 12 months; Prolonged sHRT regimen: use for more than 5 years when started in women aged ≥ 45, 12 months or more of using norethisterone or medroxyprogesterone acetate for < 10 days / month or, micronised progesterone for < 12 days / month, as part of a sequential regimen", type: "RISK_FACTOR", categories: ["GYNAECOLOGICAL"] },
  { id: "minorRiskFactorsForEndometrialCancer", name: "At least three minor risk factor for Endometrial Cancer: BMI 30-39; Unopposed estrogen > 3 months but < 6 months; Tricycling HRT (quarterly progestogen) for > 6 but < 12 months, > 6 months but < 12 months of using norethisterone or medroxyprogesteorne acetate for < 10 days / month or, micronised progesterone for < 12 days / month, as part of a sequential regimen; Where the progestogen dose is not in proportion to the estrogen dose for > 12 months (including expired 52 mg LNG-IUD); Anovulatory cycles, such as in Polycystic ovarian syndrome; Diabetes", type: "RISK_FACTOR", categories: ["GYNAECOLOGICAL"] },
  { id: "axillaLump", name: "Axilla lump", type: "SIGN", categories: ["BREAST"] },
  { id: "backPain", name: "Back pain", type: "SYMPTOM", categories: ["HAEMATOLOGICAL", "GASTROINTESTINAL"] },
  { id: "backPainRedFlags", name: "Back pain with red flag - previous malignancy, aged >40 and new onset, weight loss, previous longstanding steroid use, recent serious illness/significant infection, generalised neurological deficit, progressive spinal deformity, lytic lesion on x-ray, non-mechanical pain (worse at rest), thoracic pain, fever, rigors, generalised malaise.", type: "SYMPTOM", categories: ["HAEMATOLOGICAL"] },
  { id: "bmiAbove40", name: "BMI > 40", type: "RISK_FACTOR", categories: ["GYNAECOLOGICAL"] },
  { id: "boneMetastasesNoClearPrimary", name: "Bone metastases with no clear primary", type: "SIGN", categories: ["NON_SPECIFIC"] },
  { id: "bonePain", name: "Bone pain", type: "SYMPTOM", categories: ["BONES_AND_SOFT_TISSUES", "HAEMATOLOGICAL"] },
  { id: "boneTenderness", name: "Bone tenderness", type: "SIGN", categories: ["BONES_AND_SOFT_TISSUES"] },
  { id: "BRCA1Carrier", name: "BRCA 1 carrier", type: "RISK_FACTOR", categories: ["GYNAECOLOGICAL"] },
  { id: "BRCA2Carrier", name: "BRCA 2 carrier", type: "RISK_FACTOR", categories: ["GYNAECOLOGICAL"] },
  { id: "breastAbscess", name: "Breast abscess", type: "SIGN", categories: ["BREAST"] },
  { id: "breastAbscessNotRespondingToAntibiotics", name: "Breast abscess not responding to antibiotics", type: "SIGN", categories: ["BREAST"] },
  { id: "breastDimplingOrTethering", name: "Breast dimpling or tethering", type: "SIGN", categories: ["BREAST"] },
  { id: "breastInfectionFailsToRespondToTreatment", name: "Breast infection or inflammation that fails to respond to antibiotics", type: "RISK_FACTOR", categories: ["BREAST"] },
  { id: "breastLump", name: "Breast lump", type: "SIGN", categories: ["BREAST"] },
  { id: "discreteHardBreastLump", name: "Breast lump - discrete, hard, ±fixation, ± skin tethering", type: "SIGN", categories: ["BREAST"] },
  { id: "breastLumpPersistingAfterPeriod", name: "Breast lump - persisting after period", type: "SIGN", categories: ["BREAST"] },
  { id: "breastLumpPersistingAfterPeriodOrMenopause", name: "Breast lump - persisting after period or menopause", type: "SIGN", categories: ["BREAST"] },
  { id: "subareolarLump", name: "Breast lump - subareolar (unilateral)", type: "SIGN", categories: ["BREAST"] },
  { id: "benignBreastLump", name: "Breast lump - suggests benign (i.e. all of: smooth, well defined, mobile, unchanged)", type: "SIGN", categories: ["BREAST"] },
  { id: "breastNodularity", name: "Breast nodularity - focal or diffuse", type: "SIGN", categories: ["BREAST"] },
  { id: "breastPain", name: "Breast pain", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "breastExematousChange", name: "Breast skin changes such as eczema or rash (unresponsive to topical treatment)", type: "SIGN", categories: ["BREAST"] },
  { id: "breastUlceration", name: "Breast ulceration", type: "SIGN", categories: ["BREAST"] },
  { id: "neverTakenPartInCervicalScreening", name: "Cervical screening - never taken part or has left the programme (e.g. 65 or older)", type: "RISK_FACTOR", categories: ["GYNAECOLOGICAL"] },
  { id: "overdueForCervicalScreening", name: "Cervical screening - overdue", type: "RISK_FACTOR", categories: ["GYNAECOLOGICAL"] },
  { id: "regularAttenderOfCervicalScreening", name: "Cervical screening - regularly attends and next planned screening not due", type: "RISK_FACTOR", categories: ["GYNAECOLOGICAL"] },
  { id: "changeInBowelHabit", name: "Change in bowel habit", type: "SYMPTOM", categories: ["GASTROINTESTINAL", "GYNAECOLOGICAL"] },
  { id: "changeInCongnitiveFunction", name: "Change in cognitive function", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "shapeOfTesticle", name: "Change in shape of a testicle", type: "SIGN", categories: ["UROLOGICAL"] },
  { id: "textureOfTesticle", name: "Change in texture of a testicle", type: "SIGN", categories: ["UROLOGICAL"] },
  { id: "chestPain", name: "Chest pain", type: "SYMPTOM", categories: ["CHEST"] },
  { id: "signsLungCancer", name: "Chest signs consistent with lung cancer", type: "SIGN", categories: ["CHEST"] },
  { id: "signsPleuralDisease", name: "Chest signs consistent with pleural disease", type: "SIGN", categories: ["CHEST"] },
  { id: "chronicObstructivePulmonaryDisease", name: "Chronic obstructive pulmonary disease (COPD)", type: "RISK_FACTOR", categories: ["CHEST"] },
  { id: "clinicalSuspicionOfENTCancer", name: "Clinical suspicion of ENT cancer", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "confusion", name: "Confusion", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "constipation", name: "Constipation", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "constipationNotResponsiveToLaxatives", name: "Constipation - not responsive to laxatives", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "cough", name: "Cough", type: "SYMPTOM", categories: ["CHEST"] },
  { id: "cranialNervePalsy", name: "Cranial nerve palsy", type: "SIGN", categories: ["HEAD_AND_NECK", "NEURO_AND_EYE"] },
  { id: "cranialNervePalsyIpswich", name: "Cranial nerve palsy", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "cranialNervePalsyBury", name: "Cranial nerve palsy - unexlpained, persistent (not including tinnitus, hearing loss, anosmia, visual loss)", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "decreasedVerbalFluency", name: "Decreased verbal fluency", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "deepVeinThrombosis", name: "Deep vein thrombosis (DVT) or pulmonary embolism (PE)", type: "RISK_FACTOR", categories: ["NON_SPECIFIC"] },
  { id: "destructionOrGrowthOfCervix", name: "Destructive or obvious growth on or replacing cervix", type: "SIGN", categories: ["GYNAECOLOGICAL"] },
  { id: "diarrhoea", name: "Diarrhoea", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "doubleVision", name: "Double vision", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "dyspepsia", name: "Dyspepsia", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "dysphagia", name: "Dysphagia", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "dysphasia", name: "Dysphasia", type: "SYMPTOM", categories: ["NEURO_AND_EYE", "CHEST"] },
  { id: "dysuria", name: "Dysuria", type: "SYMPTOM", categories: ["UROLOGICAL"] },
  { id: "earlySatiety", name: "Early satiety", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "enlargingGoitre", name: "Enlarging thyroid goitre", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "erectileDysfunction", name: "Erectile dysfunction", type: "SYMPTOM", categories: ["UROLOGICAL"] },
  { id: "erythroleukoplakia", name: "Erythroleukoplakia (red and white patch in the oral cavity)", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "erythroplakia", name: "Erythroplakia (red patch in the oral cavity)", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "evidenceOfSoftTissueSarcomaRecurrence", name: "Evidence of soft tissue sarcoma recurrence", type: "SIGN", categories: ["BONES_AND_SOFT_TISSUES"] },
  { id: "extraocularMuscularPalsy", name: "Extraocular muscular palsy", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "facialMass", name: "Facial mass", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "facialNervePalsyBury", name: "Facial nerve palsy not resolving after 6 weeks", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "familyHistoryOfBreastCancer", name: "Family history of breast cancer", type: "RISK_FACTOR", categories: ["BREAST"] },
  { id: "familyHistoryOfColorectalCancer", name: "Family history of colorectal cancer", type: "RISK_FACTOR", categories: ["GASTROINTESTINAL"] },
  { id: "familyHistoryEndocrineTumours", name: "Family history of endocrine tumours", type: "RISK_FACTOR", categories: ["HEAD_AND_NECK"] },
  { id: "familyHistoryOfGICancer", name: "Family history of GI cancer (one first degree relative diagnosed under the age of 45 or two affected first degree relatives)", type: "RISK_FACTOR", categories: ["GASTROINTESTINAL"] },
  { id: "familyHistoryOfLungCancer", name: "Family history of lung cancer", type: "RISK_FACTOR", categories: ["CHEST"] },
  { id: "familyHistoryOfLynchSyndrome", name: "Family history of lynch syndrome", type: "RISK_FACTOR", categories: ["GASTROINTESTINAL"] },
  { id: "familyHistoryOfOvarianCancer", name: "Family history of ovarian cancer", type: "RISK_FACTOR", categories: ["GYNAECOLOGICAL"] },
  { id: "familyHistoryOfProstateCancer", name: "Family history of prostate cancer", type: "RISK_FACTOR", categories: ["UROLOGICAL"] },
  { id: "familyHistoryOfSkinCancer", name: "Family history of skin cancer", type: "RISK_FACTOR", categories: ["SKIN"] },
  { id: "thyroidCancerFamilyHistory", name: "Family history of thyroid cancer", type: "RISK_FACTOR", categories: ["HEAD_AND_NECK"] },
  { id: "fingerClubbing", name: "Finger clubbing", type: "SIGN", categories: ["CHEST"] },
  { id: "oralCavityFirmSubmucosalSwelling", name: "Firm submucosal swelling in the oral cavity", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "oneFirstDegreeRelativeWithColorectalCancerLessThan50", name: "First degree relative (one or more) with colorectal cancer before the age of 50 years", type: "RISK_FACTOR", categories: ["GASTROINTESTINAL"] },
  { id: "twoFirstDegreeRelativesWithColorectalCancer", name: "First degree relatives (two or more) with colorectal cancer", type: "RISK_FACTOR", categories: ["GASTROINTESTINAL"] },
  { id: "focalNeurologicalSigns", name: "Focal neurological signs", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "focalNeurologicalSymptom", name: "Focal neurological symptom", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "geneticPredispositionToCancerEndometrialCancer", name: "Genetic predisposition of endometrial cancer", type: "RISK_FACTOR", categories: ["GYNAECOLOGICAL"] },
  { id: "GPClinicalSuspicionOfCancerOrSeriousDisease", name: "GP clinical suspicion of cancer or serious disease ('gut feeling')", type: "RISK_FACTOR", categories: ["NON_SPECIFIC"] },
  { id: "gynaecomastia", name: "Gynaecomastia", type: "SIGN", categories: ["BREAST"] },
  { id: "gynaecomastiaWithNoObviousCause", name: "Gynaecomastia with no obvious physiological or drug cause (e.g. anabolic steroids, cannabis, finasteride)", type: "SIGN", categories: ["BREAST"] },
  { id: "haematemesis", name: "Haematemesis", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "acuteHaematemesis", name: "Haematemesis - acute, ongoing or large volume", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "nonAcuteHaematemesis", name: "Haematemesis - recent episode of non-acute, small volume bleeding", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "recurrentOrPersistentVisibleHaematuriaDespiteUTITreatment", name: "Haematuria - visible and recurrent or persistent despite UTI treatment", type: "SYMPTOM", categories: ["UROLOGICAL"] },
  { id: "haemoptysis", name: "Haemoptysis", type: "SYMPTOM", categories: ["CHEST"] },
  { id: "persistentHaemoptysis", name: "Haemoptysis - persistent", type: "SYMPTOM", categories: ["CHEST"] },
  { id: "headacheBury", name: "Headache (with other progressive neurological symptoms)", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "headacheOfChangedQuality", name: "Headache - altered in nature in someone with a history of headaches", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "isolatedDailyHeadacheLessThan12weeks", name: "Headache - isolated, new-onset, daily headache of less than 12 weeks duration", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "postureRelatedHeadache", name: "Headache - posture related", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "headacheProgressivelyWorsening", name: "Headache - progressively worsening", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "headacheFocalNeurologicalSymptoms", name: "Headache - with focal neurological symptoms", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "headacheWithNonFocalNeurologicalSymptoms", name: "Headache - with non-focal neurological symptoms", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "headacheWithPulseSynchronousTinnitus", name: "Headache - with pulse synchronous tinnitus", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "headacheWithSinisterFeaturesOfRaisedIntracranialPressure", name: "Headache - with sinister features of raised intracranial pressure (i.e. including nausea, vomiting, drowsiness, pulsesynchronous tinnitus, worse on supine position, awakens sleep, behavioural slowness, cognitive decline)", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "heartburn", name: "Heartburn", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "hemiFacialNumbness", name: "Hemi-facial numbness", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "hemiTongueParalysis", name: "Hemi-tongue paralysis", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "hemiparesis", name: "Hemiparesis (one-sided weakness)", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "hemisensoryLoss", name: "Hemisensory loss", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "hepatosplenomegaly", name: "Hepatosplenomegaly", type: "SIGN", categories: ["HAEMATOLOGICAL"] },
  { id: "alcoholExcessHistory", name: "History of alcohol excess", type: "RISK_FACTOR", categories: ["HEAD_AND_NECK"] },
  { id: "historyOfCancer", name: "History of any cancer", type: "RISK_FACTOR", categories: ["NEURO_AND_EYE"] },
  { id: "historyOfBreastCancer", name: "History of breast cancer", type: "RISK_FACTOR", categories: ["BREAST"] },
  { id: "neurologicalFeatureMalignancyHistory", name: "History of malignancy with neurological symptoms", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "hivInfection", name: "HIV infection", type: "RISK_FACTOR", categories: ["HEAD_AND_NECK"] },
  { id: "hpvInfection", name: "HPV infection", type: "RISK_FACTOR", categories: ["HEAD_AND_NECK"] },
  { id: "immunosuppressed", name: "Immunosuppressed (e.g. on immunosuppressive therapy)", type: "RISK_FACTOR", categories: ["SKIN"] },
  { id: "impairedHigherMentalFunction", name: "Impaired higher mental function (e.g. forgetful)", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "intermittentDrowsiness", name: "Intermittent drowsiness", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "irisNoduleGlaucomaOrCataract", name: "Iris nodule causing glaucoma or a cataract", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "irisNoduleIridoCornealAngle", name: "Iris nodule involving the irido-corneal angle", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "irisNoduleMarkedlyElevated", name: "Iris nodule markedly elevated", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "irisNodule3mmDiameter", name: "Iris nodule more than 3mm in diameter", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "irregularBleedingOnHRTOrTamoxifen", name: "Irregular bleeding persisting 6 weeks after stopping HRT or bleeding on tamoxifen after significant amenorrhoea", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "irregularBleeding", name: "Irregular menstrual bleeding", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "jaundice", name: "Jaundice", type: "SIGN", categories: ["GASTROINTESTINAL"] },
  { id: "leukoplakia", name: "Leukoplakia", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "limbAtaxia", name: "Limb ataxia", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "lipLump", name: "Lip lump", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "liverMetastasesNoClearPrimary", name: "Liver metastases with no clear primary", type: "SIGN", categories: ["NON_SPECIFIC"] },
  { id: "lowerUrinaryTractSymptoms", name: "Lower urinary tract symptoms", type: "SYMPTOM", categories: ["UROLOGICAL"] },
  { id: "lungMetastasesNoClearPrimary", name: "Lung metastases with no clear primary", type: "SIGN", categories: ["NON_SPECIFIC"] },
  { id: "axillaryLymphadenopathyBury", name: "Lymphadenopathy - axillary", type: "SIGN", categories: ["NON_SPECIFIC"] },
  { id: "inguinalLymphadenopathyBury", name: "Lymphadenopathy - inguinal", type: "SIGN", categories: ["NON_SPECIFIC"] },
  { id: "largeLymphNodes", name: "Lymphadenopathy - lymph nodes ≥ 2cm or increasing in size", type: "SIGN", categories: ["HAEMATOLOGICAL"] },
  { id: "lymphadenopathyOnImaging", name: "Lymphadenopathy - on imaging", type: "SIGN", categories: ["HAEMATOLOGICAL"] },
  { id: "cervicalLymphadenopathy", name: "Lymphadenopathy - persistent cervical", type: "SIGN", categories: ["CHEST"] },
  { id: "persistentLymphadenopathy", name: "Lymphadenopathy - persistent for ≥ 6 weeks", type: "SIGN", categories: ["HAEMATOLOGICAL"] },
  { id: "supraclavicularLymphadenopathy", name: "Lymphadenopathy - supraclavicular", type: "SIGN", categories: ["CHEST"] },
  { id: "unexplainedLymphadenopathy", name: "Lymphadenopathy - unexplained", type: "SIGN", categories: ["HAEMATOLOGICAL"] },
  { id: "lynchSyndrome", name: "Lynch syndrome", type: "RISK_FACTOR", categories: ["GYNAECOLOGICAL"] },
  { id: "malaise", name: "Malaise", type: "SYMPTOM", categories: ["NON_SPECIFIC"] },
  { id: "mastitis", name: "Mastitis", type: "SIGN", categories: ["BREAST"] },
  { id: "membersOfMEN2Families", name: "Members of MEN2 families (multiple endocrine neoplasia - type 2)", type: "RISK_FACTOR", categories: ["HEAD_AND_NECK"] },
  { id: "menorrhagia", name: "Menorrhagia", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "purulentNasalDischarge", name: "Nasal discharge - purulent", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "bloodyNasalDischarge", name: "Nasal discharge - unilateral blood stained or bloody", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "nasalMass", name: "Nasal mass", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "nausea", name: "Nausea", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "neckLump", name: "Neck lump or mass", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "newOnsetSeizures", name: "New onset seizures", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "newOnsetSeizuresSomerset", name: "New onset seizures characterised by focal seizures, prolonged post-ictal state, status epilepticus, or neurological signs between seizures", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "newOnsetSeizuresWithFocalOrInterictalFocalDeficit", name: "New onset seizures with focal or interictal focal deficit", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "irritableBowelSyndrome", name: "New symptoms of irritable bowel syndrome (IBS) in the last 12 months", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "diabetes", name: "New-onset diabetes mellitus", type: "RISK_FACTOR", categories: ["GASTROINTESTINAL"] },
  { id: "benignNippleChange", name: "Nipple - bilateral discharge or long-standing change (including persistent bilateral nipple eczema)", type: "SIGN", categories: ["BREAST"] },
  { id: "bilateralNippleInversion", name: "Nipple - bilateral inversion", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "unilateralNippleChange", name: "Nipple - other unilateral changes of concern (e.g. Paget's)", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "nippleRetractionOrDistortion", name: "Nipple - retraction or distortion of recent onset (<3 months onset)", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "nippleSpontaneosUnilateralDischargeBloody", name: "Nipple - spontaneous unilateral discharge which is bloody or blood stained", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "nippleDischargeBloodStainedOrSerous", name: "Nipple - spontaneous unilateral discharge which is bloody, blood-stained or serous", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "nippleDischargeTroublesome", name: "Nipple - spontaneous unilateral discharge which is troublesome or persistent", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "nippleDischarge", name: "Nipple - unilateral discharge", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "nippleDischargeLondon", name: "Nipple - unilateral discharge (blood or watery)", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "nippleDischargeOtherClear", name: "Nipple - unilateral discharge (other - e.g. clear)", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "nippleDischargeOther", name: "Nipple - unilateral discharge (other)", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "nippleDischargeBloodStained", name: "Nipple - unilateral discharge blood-stained", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "nippleDischargeBloody", name: "Nipple - unilateral discharge blood-stained or clear", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "nippleRetraction", name: "Nipple - unilateral retraction or inversion", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "nippleRetractionLondon", name: "Nipple - unilateral retraction or inversion", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "nippleUlceration", name: "Nipple - unilateral ulceration", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "unilateralEczemaOfNippleOrAreola", name: "Nipple or areola - unilateral eczematous skin ", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "unilateralExematousChange", name: "Nipple or areola - unilateral eczematous skin (unresponsive to topical 0.1% mometasone for 2 weeks)", type: "SIGN", categories: ["BREAST"] },
  { id: "nocturia", name: "Nocturia", type: "SYMPTOM", categories: ["UROLOGICAL"] },
  { id: "asymmetricBreastNodularityOrThickening", name: "Nodularity or thickening of the breast - asymmetric (present after menstruation)", type: "SIGN", categories: ["BREAST"] },
  { id: "nonFocalNeurologicalSymptoms", name: "Non-focal neurological symptoms", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "poorHealingToothExtraction4weeks", name: "Non-healing extraction sockets (> 4 weeks duration) or suspicious loosening of teeth (particularly if associated with numbness of the lip)", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "enlargementOfTesticle", name: "Non-painful enlargement of a testicle", type: "SIGN", categories: ["UROLOGICAL"] },
  { id: "nonSpecificAbdominalSymptoms", name: "Non-specific abdominal symptoms of more than 4 weeks duration", type: "SYMPTOM", categories: ["GASTROINTESTINAL", "UROLOGICAL", "GYNAECOLOGICAL", "NON_SPECIFIC"] },
  { id: "oculomotorNervePalsy", name: "Oculomotor nerve palsy", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "odynophagia", name: "Odynophagia (painful swallowing)", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "odynophagiaSomerset", name: "Odynophagia (painful swallowing)", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "odynophagia3weeks", name: "Odynophagia lasting at least 3 weeks", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "immunosuppressiveTherapy", name: "On immunosuppressive therapy", type: "RISK_FACTOR", categories: ["SKIN"] },
  { id: "oralCavityLump", name: "Oral cavity lump", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "oralTobaccoUse", name: "Oral tobacco use", type: "RISK_FACTOR", categories: ["HEAD_AND_NECK"] },
  { id: "orbitalMass", name: "Orbital mass", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "organTransplantRecipient", name: "Organ transplant recipient", type: "RISK_FACTOR", categories: ["SKIN"] },
  { id: "otalgia3weeks", name: "Otalgia lasting at least 3 weeks", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "otherBreastChangeOfConcern", name: "Other breast change of concern", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "otherAtypicalPain", name: "Other new atypical pain", type: "SYMPTOM", categories: ["NON_SPECIFIC"] },
  { id: "otherPain", name: "Other pain", type: "SYMPTOM", categories: ["NON_SPECIFIC"] },
  { id: "skinChangesCancerOther", name: "Other skin changes suggestive of breast cancer (e.g. peau d'orange)", type: "SIGN", categories: ["BREAST"] },
  { id: "pallor", name: "Pallor", type: "SYMPTOM", categories: ["HAEMATOLOGICAL"] },
  { id: "palpableRenalMass", name: "Palpable renal mass", type: "SIGN", categories: ["UROLOGICAL"] },
  { id: "papilloedema", name: "Papilloedema (cranial nerve)", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "paraesthesia", name: "Paraesthesia (e.g. numbness)", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "parotidLump", name: "Parotid lump", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "smoker", name: "Past or current smoker", type: "RISK_FACTOR", categories: ["CHEST"] },
  { id: "patientConcernForGeneticRiskOfBreastCancer", name: "Patient concern they have a genetic risk of cancer", type: "RISK_FACTOR", categories: ["BREAST"] },
  { id: "patientDeterioratingRapidly", name: "Patient is deteriorating rapidly and is too unwell for a suspected cancer referral but not needing acute hospital admission", type: "RISK_FACTOR", categories: ["NON_SPECIFIC"] },
  { id: "pelvicMass", name: "Pelvic mass", type: "SIGN", categories: ["GYNAECOLOGICAL"] },
  { id: "pelvicPain", name: "Pelvic pain", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "penileMass", name: "Penile mass", type: "SIGN", categories: ["UROLOGICAL"] },
  { id: "penileUlceration", name: "Penile ulceration", type: "SIGN", categories: ["UROLOGICAL"] },
  { id: "perimenopausal", name: "Perimenopausal", type: "RISK_FACTOR", categories: ["BREAST", "GYNAECOLOGICAL"] },
  { id: "persistentChestInfection", name: "Persistent chest infection", type: "RISK_FACTOR", categories: ["CHEST"] },
  { id: "breastLumpiness", name: "Persistent focal area of breast lumpiness", type: "SIGN", categories: ["BREAST"] },
  { id: "hoarseness", name: "Persistent hoarseness", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "persistentInflammatoryChange", name: "Persistent inflammatory change", type: "SIGN", categories: ["BREAST"] },
  { id: "persistentIntermenstrualBleeding", name: "Persistent intermenstrual bleeding (more than 3 months)", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "foreskinSymptoms", name: "Persistent or unexplained foreskin symptoms", type: "SYMPTOM", categories: ["UROLOGICAL"] },
  { id: "glansSymptoms", name: "Persistent or unexplained glans of the penis symptoms", type: "SYMPTOM", categories: ["UROLOGICAL"] },
  { id: "testicularSymptoms", name: "Persistent or unexplained testicular symptoms", type: "SYMPTOM", categories: ["UROLOGICAL"] },
  { id: "persistentPain", name: "Persistent pain", type: "SYMPTOM", categories: ["NON_SPECIFIC"] },
  { id: "persistentPenileLesion", name: "Persistent penile lesion after treatment for a sexually transmitted infection has been completed", type: "SIGN", categories: ["UROLOGICAL"] },
  { id: "throatDiscomfort4weeks", name: "Persistent throat discomfort lasting at least 4 weeks (particularly unilateral)", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "throatPain4weeks", name: "Persistent throat pain lasting at least 4 weeks (particularly unilateral)", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "unilateralOtalgiaWithNormalOtoscopy", name: "Persistent unilateral otalgia (with normal otoscopy)", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "unilateralOtalgia", name: "Persistent unilateral otalgia in the absence of any localising ear findings (i.e. normal otoscopy)", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "persistentUTI", name: "Persistent urinary tract infection (UTI)", type: "RISK_FACTOR", categories: ["UROLOGICAL"] },
  { id: "personalityChange", name: "Personality change", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "photoDamagedSkin", name: "Photo-damaged skin", type: "RISK_FACTOR", categories: ["SKIN"] },
  { id: "poorHealingToothExtraction3weeks", name: "Poor healing ≥ 3 weeks post tooth extraction", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "poorOralIntake", name: "Poor oral intake and at risk of dehydration", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "caudaEquinaSyndrome", name: "Possible Cauda Equina Syndrome", type: "SIGN", categories: ["UROLOGICAL"] },
  { id: "spinalCordCompression", name: "Possible malignant spinal cord compression", type: "SIGN", categories: ["HAEMATOLOGICAL"] },
  { id: "possibleProstateCancerOnDre", name: "Possible prostate cancer on digital rectal examination (DRE)", type: "SIGN", categories: ["UROLOGICAL"] },
  { id: "spinalCordCompressionLondon", name: "Possible spinal cord compression - saddle anaesthesia, reduced anal tone, hip or knee weakness, urinary retention, leg weakness, limb numbness, ataxia, bilateral leg pain, perianal sensory loss, erectile dysfunction.", type: "SIGN", categories: ["HAEMATOLOGICAL"] },
  { id: "postcoitalVaginalBleedingAny", name: "Postcoital vaginal bleeding", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "postcoitalVaginalBleeding", name: "Postcoital vaginal bleeding (in premenopausal women)", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "postmenopausal", name: "Postmenopausal", type: "RISK_FACTOR", categories: ["GYNAECOLOGICAL"] },
  { id: "postmenopausalSomerset", name: "Postmenopausal", type: "RISK_FACTOR", categories: ["GASTROINTESTINAL", "GYNAECOLOGICAL"] },
  { id: "postMenopausalVaginalBleeding", name: "Postmenopausal vaginal bleeding (bleeding >12 months after menses have stopped)", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "postMenopausalVaginalBleedingAfterHRT", name: "Postmenopausal vaginal bleeding - 4-6 weeks after starting HRT (it is normal to bleed up to 4 weeks after starting HRT or changing preparations)", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "postMenopausalVaginalBleedingAfter6WeeksHRTCessation", name: "Postmenopausal vaginal bleeding - >6 months after start or change of HRT", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "postMenopausalVaginalBleedingAfterHRTCessation", name: "Postmenopausal vaginal bleeding - after cessation of HRT for 6 weeks OR taking tamoxifen", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "unscheduledBleedingOnSystemicHRT", name: "Postmenopausal vaginal bleeding - unscheduled bleeding on systemic HRT", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "postMenopausalVaginalBleedingOnTamoxifen", name: "Postmenopausal vaginal bleeding or irregular bleeding - in patients taking Tamoxifen", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "prePuberty", name: "Pre-puberty", type: "RISK_FACTOR", categories: ["HEAD_AND_NECK"] },
  { id: "premenopausal", name: "Premenopausal", type: "RISK_FACTOR", categories: ["BREAST", "GYNAECOLOGICAL"] },
  { id: "myelomaPresentation", name: "Presentation consistent with myeloma", type: "SYMPTOM", categories: ["HAEMATOLOGICAL"] },
  { id: "previousHeadAndNeckCancer", name: "Previous head and neck cancer", type: "RISK_FACTOR", categories: ["HEAD_AND_NECK"] },
  { id: "previousHistoryOfCancer", name: "Previous history of cancer", type: "RISK_FACTOR", categories: ["NON_SPECIFIC"] },
  { id: "hysterectomy", name: "Previous hysterectomy", type: "RISK_FACTOR", categories: ["GYNAECOLOGICAL"] },
  { id: "headAndNeckPreviousIrradiation", name: "Previous irradiation to the head and neck (e.g. previous exposure to radiotherapy for lymphoma)", type: "RISK_FACTOR", categories: ["HEAD_AND_NECK"] },
  { id: "previousNeckIrradiation", name: "Previous irradiation to the neck (e.g. previous exposure to radiotherapy for lymphoma)", type: "RISK_FACTOR", categories: ["HEAD_AND_NECK"] },
  { id: "previousSkinCancer", name: "Previous skin cancer", type: "RISK_FACTOR", categories: ["SKIN"] },
  { id: "progressiveChangeInBreastSizeWithOedema", name: "Progressive change in breast size with signs of oedema", type: "SIGN", categories: ["BREAST"] },
  { id: "progressiveNeurologicalDeficit", name: "Progressive neurological deficit", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "progressivePain", name: "Progressive pain", type: "SYMPTOM", categories: ["NON_SPECIFIC"] },
  { id: "centralNeurologicalFunctionProgressiveSubAcuteLoss", name: "Progressive sub-acute loss of central neurological function (e.g. weakness, sensory loss, dysphasia, ataxia, visual disturbance)", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "progressiveWeakness", name: "Progressive weakness", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "proptosisOrGlobalDisplacementOfTheEye", name: "Proptosis or global displacement of the eye", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "rapidEnlargementOfThyroid", name: "Rapid enlargement of the thyroid", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "rapidPersonalityOrBehaviourChange", name: "Rapid personality, behaviour change or slowness confirmed by witness with no reasonable explanation", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "raipdlyWorseningDiabetes", name: "Rapidly worsening diabetes", type: "RISK_FACTOR", categories: ["GASTROINTESTINAL"] },
  { id: "rectalBleeding", name: "Rectal bleeding", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "darkRedBloodMixedInWithStool", name: "Rectal bleeding - dark red blood mixed in with stool", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "rectalBleedingFresh", name: "Rectal bleeding - fresh blood", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "rectalMass", name: "Rectal mass", type: "SIGN", categories: ["GASTROINTESTINAL"] },
  { id: "recurrentBreastCyst", name: "Recurrent breast cyst", type: "SIGN", categories: ["BREAST"] },
  { id: "recurrentChestInfection", name: "Recurrent chest infection", type: "RISK_FACTOR", categories: ["CHEST"] },
  { id: "recurrentUTI", name: "Recurrent urinary tract infections (UTIs)", type: "RISK_FACTOR", categories: ["UROLOGICAL"] },
  { id: "reflux", name: "Reflux", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "regurgitation", name: "Regurgitation", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "renalMass", name: "Renal mass", type: "SIGN", categories: ["UROLOGICAL"] },
  { id: "rigors", name: "Rigors", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "sensationOfLumpInThroat", name: "Sensation of a lump in the throat", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "serosanguinousNasalDischarg3weeks", name: "Serosanguinous nasal discharge lasting more than 3 weeks", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "severeFacialPain", name: "Severe facial pain", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "severeUnexplainedFatigue", name: "Severe unexplained fatigue", type: "SYMPTOM", categories: ["NON_SPECIFIC"] },
  { id: "shoulderPain", name: "Shoulder pain", type: "SYMPTOM", categories: ["CHEST"] },
  { id: "significantGPConcern", name: "Significant GP concern for cancer", type: "RISK_FACTOR", categories: ["NON_SPECIFIC"] },
  { id: "signsOfAdvancedOrMetastaticProstateCancer", name: "Signs of advanced or metastatic prostate cancer", type: "SIGN", categories: ["UROLOGICAL"] },
  { id: "signsOfAnIntraocularTumourOnFundoscopy", name: "Signs of an intraocular tumour on fundoscopy", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "paraneoplasticSigns", name: "Signs of paraneoplastic disease", type: "SIGN", categories: ["CHEST", "NON_SPECIFIC"] },
  { id: "signsOfSvcObstruction", name: "Signs of SVC obstruction", type: "SIGN", categories: ["CHEST"] },
  { id: "skeletalPain", name: "Skeletal pain", type: "SYMPTOM", categories: ["CHEST"] },
  { id: "skinChangesCancer", name: "Skin changes suggestive of breast cancer (including nodules, distortion, ulceration, tethering, peau d'orange, dimpling)", type: "SIGN", categories: ["BREAST"] },
  { id: "softtissueMassMoreThan5cm", name: "Soft tissue mass - 5cm or more", type: "SIGN", categories: ["BONES_AND_SOFT_TISSUES"] },
  { id: "softTissueMassDeepToFascia", name: "Soft tissue mass - deep to fascia", type: "SIGN", categories: ["BONES_AND_SOFT_TISSUES"] },
  { id: "recurrenceOfLumpFollowingExcision", name: "Soft tissue mass - evidence of recurrence following excision", type: "SIGN", categories: ["BONES_AND_SOFT_TISSUES"] },
  { id: "softTissueMassFixed", name: "Soft tissue mass - fixed", type: "SIGN", categories: ["BONES_AND_SOFT_TISSUES"] },
  { id: "softTissueMassImmobile", name: "Soft tissue mass - immobile", type: "SIGN", categories: ["BONES_AND_SOFT_TISSUES"] },
  { id: "softtissueMassLessThan5cm", name: "Soft tissue mass - less than 5cm", type: "SIGN", categories: ["BONES_AND_SOFT_TISSUES"] },
  { id: "unexplainedLumpMoreThan5cm", name: "Soft tissue mass - more than 5cm in size", type: "SIGN", categories: ["BONES_AND_SOFT_TISSUES"] },
  { id: "softTissueMassPainful", name: "Soft tissue mass - painful", type: "SYMPTOM", categories: ["BONES_AND_SOFT_TISSUES"] },
  { id: "solidIntratesticularLump", name: "Solid intra-testicular lump", type: "SIGN", categories: ["UROLOGICAL"] },
  { id: "unexplainedSplenomegaly", name: "Splenomegaly", type: "SIGN", categories: ["HAEMATOLOGICAL"] },
  { id: "steatorrhoea", name: "Steatorrhoea", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "stridor", name: "Stridor", type: "SYMPTOM", categories: ["CHEST"] },
  { id: "strongFamilyHistoryOfBreastCancer", name: "Strong family history of breast cancer", type: "RISK_FACTOR", categories: ["BREAST"] },
  { id: "suddenOnsetNeurologicalDeficit", name: "Sudden onset neurological deficit", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "suspiciousVaginalLesion", name: "Supicious vaginal lesion", type: "SIGN", categories: ["GYNAECOLOGICAL"] },
  { id: "suspicionOfAMelanocyticChoroidalTumour", name: "Suspected choroidal melanoma - mushroom shape; orange pigment (lipofuscin) forming discrete clumps; large size (i.e. tumour diameter >4 disc diameters); enlargement confirmed by sequential imaging of the tumour; subretinal fluid, especially if causing blurred, distorted vision or photopsia (seeing a 'ball of lights')", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "suspectedConjunctivalMalignancy", name: "Suspected conjunctival malignancy - Pigmented or amelanotic tumour >5mm in diameter; Feeder blood vessels or visible intra-tumoural vasculature; Diffuse conjunctival and/or corneal pigmentation; thin corneal ‘frosty’ lesion(s), keratin plaque on tumour surface; Salmon pink tumour (especially in fornix or caruncular area), suggestive of lymphoma; History of recent growth, especially in adults", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "suspectedIrisMalignancy", name: "Suspected iris malignancy - tumour is > 5mm in diameter and/or > 1mm thick; diffuse tumour with indistinct margins, with or without tumour seeding onto iris surface or angle; Secondary glaucoma or cataract; tumour involves angle, possibly with ciliary body involvement (which usually causes dilated episcleral vessels)", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "kaposiSarcomaSuspected", name: "Suspected Kaposi's sarcoma in HIV patients", type: "SIGN", categories: ["BONES_AND_SOFT_TISSUES"] },
  { id: "suspectedmetastaticDisease", name: "Suspected metastatic disease", type: "SIGN", categories: ["NON_SPECIFIC"] },
  { id: "suspectedOrbitalMalignancy", name: "Suspected orbital malignancy - Proptosis or globe displacement (especially of recent onset)", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "suspicionOtherIntraocularMalignancy", name: "Suspected other intra-ocular malignancy - Suspected intraocular metastasis if specialist ocular oncology is required; Suspected retinal lymphoma (ocular symptoms and previous CNS lymphoma, uveitis not responding to therapy); CT/MRI showing an intraocular tumour; Retinoblastoma, if loss of red reflex in an infant or child, especially with family history of this cancer", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "suspectedRecurrenceOfBreastCancer", name: "Suspected recurrence of previous breast cancer", type: "SIGN", categories: ["BREAST"] },
  { id: "suspectedRetroperitonealMass", name: "Suspected retroperitoneal mass", type: "SIGN", categories: ["BONES_AND_SOFT_TISSUES"] },
  { id: "suspectedSoftTissueSarcoma", name: "Suspected soft tissue sarcoma", type: "SIGN", categories: ["BONES_AND_SOFT_TISSUES"] },
  { id: "maxillarySinusAbnormality", name: "Suspicion of maxillary sinus cancer", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "nasalAbnormality", name: "Suspicion of nasal cancer", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "postNasalSpaceAbnormality", name: "Suspicion of post-nasal space cancer", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "recurrenceOfKnownGynaecologicalCancer", name: "Suspicion of recurrence of known gynaecological cancer ", type: "SIGN", categories: ["GYNAECOLOGICAL"] },
  { id: "salivaryGlandAbnormality", name: "Suspicion of salivary gland cancer", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "suspiciousFacialPain", name: "Suspicious facial pain", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "trachealCompression", name: "Symptoms of tracheal compression", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "takingHormonalContraceptive", name: "Taking hormonal contraceptive", type: "RISK_FACTOR", categories: ["BREAST", "GYNAECOLOGICAL"] },
  { id: "takingHormoneReplacementTherapy", name: "Taking hormone replacement therapy (HRT)", type: "RISK_FACTOR", categories: ["GYNAECOLOGICAL", "BREAST"] },
  { id: "takingTamoxifen", name: "Taking tamoxifen", type: "RISK_FACTOR", categories: ["BREAST", "GYNAECOLOGICAL"] },
  { id: "testicularLump", name: "Testicular lump", type: "SIGN", categories: ["UROLOGICAL"] },
  { id: "testicularMass", name: "Testicular mass", type: "SIGN", categories: ["UROLOGICAL"] },
  { id: "throatLump", name: "Throat lump or mass", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "thromboticEvent", name: "Thrombotic episodes (e.g visual loss)", type: "SIGN", categories: ["HAEMATOLOGICAL"] },
  { id: "thyroidNoduleAssociatedWithLocalLymphadenopathy", name: "Thyroid lump or nodule - associated with local lymphadenopathy", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "thyroidNoduleIncreasingInSize", name: "Thyroid lump or nodule - increasing in size", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "longstandingThyroidNoduleWithSuddenRecentChangeInSize", name: "Thyroid lump or nodule - longstanding with sudden recent change in size", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "thyroidSolitaryNoduleDorset", name: "Thyroid lump or nodule - solitary", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "thyroidNoduleSolitary", name: "Thyroid lump or nodule - solitary (≥1cm)", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "thyroidLump", name: "Thyroid lump or nodule - unexplained", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "thyroidSwelling", name: "Thyroid swelling", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "lumpOrUlcerationOfTonsilOrOropharynx", name: "Tonsil or oropharynx lump or ulceration", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "nonPeriodontalDiseaseToothMobility", name: "Tooth mobility not associated with periodontal disease", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "treatmentResistantDyspepsia", name: "Treatment-resistant dyspepsia", type: "RISK_FACTOR", categories: ["GASTROINTESTINAL"] },
  { id: "blackout", name: "Unexplained blackouts", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "unexplainedBruising", name: "Unexplained bruising", type: "SYMPTOM", categories: ["HAEMATOLOGICAL"] },
  { id: "worseningSymptomsInExistingChronicRespiratoryCondition", name: "Unexplained changes in existing symptoms of chronic respiratory condition", type: "RISK_FACTOR", categories: ["CHEST"] },
  { id: "unexplainedFever", name: "Unexplained fever", type: "SYMPTOM", categories: ["HAEMATOLOGICAL"] },
  { id: "unexplainedFracture", name: "Unexplained fracture (i.e. spontaneous or pathological suspected)", type: "RISK_FACTOR", categories: ["HAEMATOLOGICAL", "BONES_AND_SOFT_TISSUES"] },
  { id: "unexplainedLooseningOfTeeth", name: "Unexplained loosening of teeth", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "parotidSwelling", name: "Unexplained or persistent parotid swelling", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "submandibularSwelling", name: "Unexplained or persistent submandibular swelling", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "oralUlceration3weeks", name: "Unexplained oral ulceration lasting more than 3 weeks", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "cranialNervePalsySomerset", name: "Unexplained persistent cranial neuropathies", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "soreThroat", name: "Unexplained persistent sore throat (e.g. more than 3 weeks)", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "soreThroat6Weeks", name: "Unexplained persistent sore throat for >6 weeks", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "unexplainedPetechiae", name: "Unexplained petechiae", type: "SIGN", categories: ["HAEMATOLOGICAL"] },
  { id: "unexplainedRapidCognitiveChanges", name: "Unexplained rapid cognitive changes", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "unexplainedRecurrentInfection", name: "Unexplained recurrent infection", type: "RISK_FACTOR", categories: ["HAEMATOLOGICAL"] },
  { id: "serousOtitisMediaLondon", name: "Unexplained unilateral middle ear effusion at otoscopy", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "serousOtitisMedia", name: "Unexplained unilateral serous otitis media/effusion", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "worseningOfPain", name: "Unexplained worsening of pain", type: "SYMPTOM", categories: ["NON_SPECIFIC"] },
  { id: "unilateralDeafness", name: "Unilateral deafness", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "unilateralEpistaxisWithDischargeOrObstruction", name: "Unilateral epistaxis (nose bleed) with unilateral (bloody) discharge or obstruction for > 3 weeks", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "bloodyDischargeUnilateralNasalObstruction", name: "Unilateral epistaxis (nose bleed), or unilateral obstruction with bloody discharge", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "unilateralHeadNeckPain", name: "Unilateral head and neck pain for 3 weeks or more", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "unilateralNasalObstructionBury", name: "Unilateral nasal obstruction", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "purulentDischargeUnilateralNasalObstruction", name: "Unilateral nasal obstruction associated with purulent discharge", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "referredOtalgia", name: "Unilateral pain radiating to the ear (referred otalgia)", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "unilateralSensorineuralDeafness", name: "Unilateral sensorineural deafness", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "unilateralSoreThroat", name: "Unilateral sore throat", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "tonsilarEnlargementOrUlceration", name: "Unilateral tonsilar enlargement and/or ulceration", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "unilateralNonCyclicalBreastPain", name: "Unilateral, non-cyclical breast pain beyond one mentrual cycle", type: "SYMPTOM", categories: ["BREAST"] },
  { id: "unscheduledVaginalBleeding", name: "Unscheduled vaginal bleeding", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "unscheduledVaginalBleedingPlusRiskFactor", name: "Unscheduled vaginal bleeding with increased risk factors (e.g. obesity, polycystic ovary syndrome, history of tamoxifen use or unopposed oestrogen)", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "urinaryFrequency", name: "Urinary frequency", type: "SYMPTOM", categories: ["GYNAECOLOGICAL", "UROLOGICAL"] },
  { id: "urinaryHesitancy", name: "Urinary hesitancy", type: "SYMPTOM", categories: ["UROLOGICAL"] },
  { id: "urinaryRetention", name: "Urinary retention", type: "SYMPTOM", categories: ["UROLOGICAL"] },
  { id: "urinaryUrgency", name: "Urinary urgency", type: "SYMPTOM", categories: ["GYNAECOLOGICAL", "UROLOGICAL"] },
  { id: "vaginalDischargeFirstPresentation", name: "Vaginal discharge - first presentation", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "vaginalDischarge", name: "Vaginal discharge - unexplained", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "vaginalMass", name: "Vaginal mass", type: "SIGN", categories: ["GYNAECOLOGICAL"] },
  { id: "visiblePharyngealTonsillarMass", name: "Visible pharyngeal or tonsillar mass", type: "SIGN", categories: ["HEAD_AND_NECK"] },
  { id: "visionChanges", name: "Vision changes", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "visionLossFromSuspectedOcularLesion", name: "Vision loss from suspected ocular lesion", type: "SIGN", categories: ["NEURO_AND_EYE"] },
  { id: "visualDisturbance", name: "Visual disturbance", type: "SYMPTOM", categories: ["NEURO_AND_EYE"] },
  { id: "voiceChanges", name: "Voice changes", type: "SYMPTOM", categories: ["HEAD_AND_NECK"] },
  { id: "vomiting", name: "Vomiting", type: "SYMPTOM", categories: ["GASTROINTESTINAL"] },
  { id: "vulvarBleeding", name: "Vulval bleeding", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "vulvalLesion", name: "Vulval lesion", type: "SIGN", categories: ["GYNAECOLOGICAL"] },
  { id: "vulvarLump", name: "Vulval lump", type: "SIGN", categories: ["GYNAECOLOGICAL"] },
  { id: "vulvalPruritusOrPain", name: "Vulval pruritus or pain", type: "SYMPTOM", categories: ["GYNAECOLOGICAL"] },
  { id: "vulvarUlceration", name: "Vulval ulceration", type: "SIGN", categories: ["GYNAECOLOGICAL"] },
  { id: "weightLoss", name: "Weight loss", type: "SYMPTOM", categories: ["GYNAECOLOGICAL", "GASTROINTESTINAL", "CHEST", "HAEMATOLOGICAL", "NON_SPECIFIC"] },
  { id: "wheeze", name: "Wheeze", type: "SYMPTOM", categories: ["CHEST"] },
];
